#!/bin/bash
yum install httpd -y
service httpd start 
yum install unzip -y
curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
unzip awscli-bundle.zip
sudo ./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws

aws s3 cp s3://<bucket_name> /var/www/html --region ap-south-1 --recursive
